pod 'IQKeyboardManager'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'BaiduMapAPI'
pod 'NSData+Base64'
pod 'FXBlurView'
pod 'QBPopupMenu'
pod 'MJRefresh'
pod 'EGOCache'
pod 'PNChart'
pod 'Google-Maps-iOS-SDK', '~> 1.9.2'